require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/splashes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Splash. As you add validations to Splash, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Splash.create! valid_attributes
      get splashes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      splash = Splash.create! valid_attributes
      get splash_url(splash)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_splash_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      splash = Splash.create! valid_attributes
      get edit_splash_url(splash)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Splash" do
        expect {
          post splashes_url, params: { splash: valid_attributes }
        }.to change(Splash, :count).by(1)
      end

      it "redirects to the created splash" do
        post splashes_url, params: { splash: valid_attributes }
        expect(response).to redirect_to(splash_url(Splash.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Splash" do
        expect {
          post splashes_url, params: { splash: invalid_attributes }
        }.to change(Splash, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post splashes_url, params: { splash: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested splash" do
        splash = Splash.create! valid_attributes
        patch splash_url(splash), params: { splash: new_attributes }
        splash.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the splash" do
        splash = Splash.create! valid_attributes
        patch splash_url(splash), params: { splash: new_attributes }
        splash.reload
        expect(response).to redirect_to(splash_url(splash))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        splash = Splash.create! valid_attributes
        patch splash_url(splash), params: { splash: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested splash" do
      splash = Splash.create! valid_attributes
      expect {
        delete splash_url(splash)
      }.to change(Splash, :count).by(-1)
    end

    it "redirects to the splashes list" do
      splash = Splash.create! valid_attributes
      delete splash_url(splash)
      expect(response).to redirect_to(splashes_url)
    end
  end
end
